name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/flutter/plugins/tree/master/packages/camera/camera
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.9.4+5
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
      ios:
        pluginClass: CameraPlugin

dependencies:
  camera_platform_interface:
    git:
      url: git@github.com:alien190/plugins.git
      path: packages/camera/camera_platform_interface
      ref: 07932429b91c569f4f2becd4a634680b7d1593f5

  flutter:
    sdk: flutter
  pedantic: ^1.10.0
  quiver: ^3.1.0
  flutter_plugin_android_lifecycle: ^2.0.6
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^5.2.0
  plugin_platform_interface: ^2.1.2
  video_player: ^2.4.2
