name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  camera:
    path: ../
#    git:
#      url: git@github.com:alien190/plugins
#      path: packages/camera/camera
#      ref: 2940e2687c0833a5bad187daa587636006442d09
  path_provider: ^2.0.0
  flutter:
    sdk: flutter
  video_player: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true
